AJAXHomePage/Controllers/CityController.cs
using AJAXHomePage.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AJAXHomePage.Controllers
{
    public class CityController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CityController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var customers = await _context.Customers
                .Include(c => c.Country)
                .Include(c => c.City)
                .AsNoTracking() 
                .OrderBy(c => c.City.Name)
                .ToListAsync();

            return View(customers);
        }
    }
}

AJAXHomePage/Controllers/CountryController.cs
using AJAXHomePage.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AJAXHomePage.Controllers
{
    public class CountryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CountryController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var customers = await _context.Customers
                .Include(c => c.Country)
                .Include(c => c.City)
                .OrderBy(c => c.Country.Name)
                .ToListAsync();

            return View(customers);
        }
    }
}

AJAXHomePage/Controllers/CustomerController.cs
using AJAXHomePage.Data;
using AJAXHomePage.Models;
using AJAXHomePage.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AJAXHomePage.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<CustomerController> _logger;

        public CustomerController(
            ApplicationDbContext context, 
            IWebHostEnvironment webHostEnvironment,
            ILogger<CustomerController> logger)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            var customers = await _context.Customers
                .Include(c => c.Country)
                .Include(c => c.City)
                .ToListAsync();

            return View(customers);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.Country)
                .Include(c => c.City)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (customer == null)
            {
                return NotFound();
            }

            var viewModel = new CustomerDetailsVM
            {
                Id = customer.Id,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                Email = customer.Email,
                CountryName = customer.Country.Name,
                CityName = customer.City.Name,
                ProfileImage = customer.ProfileImage
            };

            return View(viewModel);
        }


        public IActionResult Create()
        {
            var viewModel = new CustomerCreateVM
            {
                Countries = new SelectList(_context.Countries, "Id", "Name")
            };
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerCreateVM viewModel)
        {
            try
            {

                ModelState.Remove(nameof(viewModel.Countries));
                ModelState.Remove(nameof(viewModel.Cities));


                var existingCustomer = await _context.Customers
                    .FirstOrDefaultAsync(c =>
                        c.FirstName == viewModel.FirstName &&
                        c.LastName == viewModel.LastName &&
                        c.Email == viewModel.Email);

                if (existingCustomer != null)
                {
                    ModelState.AddModelError("", "A customer with these details already exists.");
                    viewModel.Countries = new SelectList(_context.Countries, "Id", "Name", viewModel.CountryId);
                    if (viewModel.CountryId > 0)
                    {
                        viewModel.Cities = new SelectList(
                            _context.Cities.Where(c => c.CountryId == viewModel.CountryId),
                            "Id", "Name", viewModel.CityId);
                    }
                    return View(viewModel);
                }

                if (ModelState.IsValid)
                {
                    string uniqueFileName = null;
                    if (viewModel.ProfileImage != null)
                    {
                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        Directory.CreateDirectory(uploadsFolder);
                        uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.ProfileImage.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await viewModel.ProfileImage.CopyToAsync(fileStream);
                        }
                    }

                    var customer = new Customer
                    {
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        Email = viewModel.Email,
                        CountryId = viewModel.CountryId,
                        CityId = viewModel.CityId,
                        ProfileImage = uniqueFileName
                    };

                    _context.Customers.Add(customer);
                    await _context.SaveChangesAsync();
                    
                    _context.ChangeTracker.Clear();

                    _logger.LogInformation("Customer created: {FirstName} {LastName}", customer.FirstName, customer.LastName);

                    TempData["Message"] = "Customer created successfully!";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating customer");
                ModelState.AddModelError("", "Unable to create customer. Please try again.");
            }

            viewModel.Countries = new SelectList(_context.Countries, "Id", "Name", viewModel.CountryId);
            if (viewModel.CountryId > 0)
            {
                viewModel.Cities = new SelectList(
                    _context.Cities.Where(c => c.CountryId == viewModel.CountryId),
                    "Id", "Name", viewModel.CityId);
            }
            return View(viewModel);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }

            var viewModel = new CustomerEditVM
            {
                Id = customer.Id,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                Email = customer.Email,
                CountryId = customer.CountryId,
                CityId = customer.CityId,
                ExistingImagePath = customer.ProfileImage,
                Countries = new SelectList(_context.Countries, "Id", "Name", customer.CountryId),
                Cities = new SelectList(_context.Cities.Where(c => c.CountryId == customer.CountryId), "Id", "Name", customer.CityId)
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CustomerEditVM viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var customer = await _context.Customers.FindAsync(id);
                    if (customer == null)
                    {
                        return NotFound();
                    }

                    customer.FirstName = viewModel.FirstName;
                    customer.LastName = viewModel.LastName;
                    customer.Email = viewModel.Email;
                    customer.CountryId = viewModel.CountryId;
                    customer.CityId = viewModel.CityId;

                    if (viewModel.ProfileImage != null)
                    {
                        if (!string.IsNullOrEmpty(customer.ProfileImage))
                        {
                            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", customer.ProfileImage);
                            if (System.IO.File.Exists(filePath))
                            {
                                System.IO.File.Delete(filePath);
                            }
                        }

                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.ProfileImage.FileName;
                        string newFilePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(newFilePath, FileMode.Create))
                        {
                            viewModel.ProfileImage.CopyTo(fileStream);
                        }
                        customer.ProfileImage = uniqueFileName;
                    }

                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(viewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            viewModel.Countries = new SelectList(_context.Countries, "Id", "Name", viewModel.CountryId);
            viewModel.Cities = new SelectList(_context.Cities.Where(c => c.CountryId == viewModel.CountryId), "Id", "Name", viewModel.CityId);
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.Country)
                .Include(c => c.City)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {

AJAXHomePage/Views/Shared/_CustomerList.cshtml
@model IEnumerable<AJAXHomePage.Models.Customer>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@{
    var token = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<input type="hidden" name="__RequestVerificationToken" value="@token" />

<table class="table">
    <thead>
        <tr>
            <th>Profile</th>
            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
            <th>@Html.DisplayNameFor(model => model.LastName)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
            <th>@Html.DisplayNameFor(model => model.Country)</th>
            <th>@Html.DisplayNameFor(model => model.City)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.ProfileImage))
                    {
                        <img src="~/images/@item.ProfileImage" alt="Profile" class="img-thumbnail" style="max-width: 50px;" />
                    }
                </td>
                <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.Country.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.City.Name)</td>
                <td>
                    <div class="btn-group">
                        <a asp-controller="Customer" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Edit</a>
                        <a asp-controller="Customer" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info">Details</a>
                        <button type="button" class="btn btn-sm btn-danger" onclick="showDeleteModal(@item.Id, '@item.FirstName @item.LastName')">Delete</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete customer <strong id="customerNameToDelete"></strong>?</p>
                <p class="text-danger">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDeleteBtn">Delete</button>
            </div>
        </div>
    </div>
</div>

AJAXHomePage/Views/Shared/_Footer.cshtml
<div class="container">
    &copy; @DateTime.Now.Year - AJAXHomePage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
</div>

AJAXHomePage/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AJAXHomePage</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

AJAXHomePage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AJAXHomePage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AJAXHomePage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Header")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @await Html.PartialAsync("_Footer")
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>